version: '3.8'

services:
  postgres:
    container_name: 'pogo-pg'
    image: postgres:17
    environment:
      POSTGRES_USER: pogo
      POSTGRES_PASSWORD: pogo
      POSTGRES_DB: pogo
    ports:
      - "127.0.0.6:5432:5432"
